spring:
  datasource:
    url: jdbc:mariadb://184.73.138.50:3306/asustest
    username: asus
    password: asus
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/dbchangelog.xml
    enabled: true
