spring:
  datasource:
    url: jdbc:mariadb://172.31.85.50:3306/asusgittest
    username: asus
    password: asus
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/dbchangelog.xml
    enabled: true
